name: Extract Text

on:
  workflow_dispatch:
    inputs:
      JP_Enabled: { type: boolean, default: false }
      GL_Enabled: { type: boolean, default: false }
      CN_Enabled: { type: boolean, default: false }
  repository_dispatch:
    types: [Extract]

permissions:
  contents: write

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      run_jobs: ${{ steps.set-matrix.outputs.run_jobs }}
      gl: ${{ steps.detect.outputs.gl }}
      jp: ${{ steps.detect.outputs.jp }}
    steps:
      - name: Detect Trigger Source
        id: detect
        run: |
          if [ "${{ github.event_name }}" = "repository_dispatch" ]; then
            echo "jp=${{ github.event.client_payload.JP_enabled || 'false' }}" >> $GITHUB_OUTPUT
            echo "gl=${{ github.event.client_payload.GL_enabled || 'false' }}" >> $GITHUB_OUTPUT
            echo "cn=${{ github.event.client_payload.CN_enabled || 'false' }}" >> $GITHUB_OUTPUT
          else
            echo "jp=${{ github.event.inputs.JP_Enabled }}" >> $GITHUB_OUTPUT
            echo "gl=${{ github.event.inputs.GL_Enabled }}" >> $GITHUB_OUTPUT
            echo "cn=${{ github.event.inputs.CN_Enabled }}" >> $GITHUB_OUTPUT
          fi

      - name: Generate Strategy Matrix
        id: set-matrix
        run: |
          MATRIX=$(jq -nc \
            --arg jp "${{ steps.detect.outputs.jp }}" \
            --arg gl "${{ steps.detect.outputs.gl }}" \
            --arg cn "${{ steps.detect.outputs.cn }}" \
            '[
              {id: "JP", name: "日服", enabled: $jp},
              {id: "GL", name: "国际服", enabled: $gl},
              {id: "CN", name: "国服", enabled: $cn}
            ] | map(select(.enabled == "true" or .enabled == true))')
          
          COUNT=$(echo $MATRIX | jq '. | length')
          echo "matrix=$MATRIX" >> $GITHUB_OUTPUT
          echo "run_jobs=$COUNT" >> $GITHUB_OUTPUT

  deploy:
    needs: setup
    if: needs.setup.outputs.run_jobs != '0'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.setup.outputs.matrix) }}
    
    name: Extract (${{ matrix.id }})
    steps:
      - name: Checkout Tool Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure SSH Access
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts

      - name: Clone Required Repositories
        run: |
          git clone --depth 1 https://x-access-token:${{ secrets.APK_SRC_REPO }}@github.com/beichen23333/BlueArchive-Translation.git BlueArchive-Translation
          git clone --depth 1 --branch ${{ matrix.id }} https://x-access-token:${{ secrets.APK_SRC_REPO }}@github.com/bluearchive-cafe/BA-Text.git BA-Text
          git clone --depth 1 --branch ${{ matrix.id }} git@github.com:roundRekt/BA-Assets-TableBundles.git Assets-Repo

      - name: Prepare Workspace
        run: |
          mv BlueArchive-Translation/* .
          rm -rf BlueArchive-Translation
          rm -rf BA-Text/Revise BA-Text/New BA-Text/Translation

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Get Version info
        id: v
        run: |
          SERVER_ID_LOWER=$(echo "${{ matrix.server.id }}" | tr '[:upper:]' '[:lower:]')
          bash other/version.sh ${{ matrix.server.id }} info_${SERVER_ID_LOWER}.json >> "$GITHUB_OUTPUT"

      - name: Get Previous Version Info
        id: prev_v
        run: |
          SERVER_ID_LOWER=$(echo "${{ matrix.server.id }}" | tr '[:upper:]' '[:lower:]')
          ORIGINAL_FILE="info_${SERVER_ID_LOWER}.json"
          TEMP_FILE="prev_${ORIGINAL_FILE}"

          git show HEAD^:"$ORIGINAL_FILE" > "$TEMP_FILE"

          bash other/version.sh ${{ matrix.server.id }} "$TEMP_FILE" >> "$GITHUB_OUTPUT"

      - name: Run Extraction
        run: |
          NEW_ZIP="Assets-Repo/${{ matrix.name }}${{ setps.v.outputs.BA_VERSION_NAME }}.zip"
          OLD_ZIP="Assets-Repo/${{ matrix.name }}${{ setps.prev_v.outputs.BA_VERSION_NAME }}.zip"
          python -m tools.extract "$NEW_ZIP" "$OLD_ZIP" "./BA-Text" other/config.json 10

      - name: Commit and Push to BA-Text
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          cd BA-Text
          git add .
          git commit -m "Extract ${{ matrix.id }} text: ${{ setps.v.outputs.BA_VERSION_NAME }} (from ${{ setps.prev_v.outputs.BA_VERSION_NAME }})" || exit 0
          git push origin ${{ matrix.id }}

  Final:
    name: 部署
    needs: [setup, deploy]
    runs-on: ubuntu-latest
    steps:

      - name: Deploy Translation
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/dispatches \
            -d '{"event_type": "Translation","client_payload": {"file_path": "BA-Text/New","output_path": "BA-Text/Translation", "batch_size": "20","max_workers": "10"}}'
